language: node_js
node_js: node
install:
  - npm install --no-optional
  - npm install -g gulp-cli
script:
  - npm run chrome
  - npm run firefox
cache:
  directories:
    - node_modules
notifications:
  email: true
branches:
  only:
    - master
